export const shopCategories = [
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'electronics', label: 'Electronics & Gadgets' },
  { value: 'grocery', label: 'Grocery & Supermarkets' },
  { value: 'restaurant', label: 'Restaurants & Cafes' },
  { value: 'beauty', label: 'Beauty & Personal Care' },
  { value: 'furniture', label: 'Furniture & Home Decor' },
  { value: 'books', label: 'Books & Stationery' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'sports', label: 'Sports & Fitness' },
  { value: 'hardware', label: 'Hardware & Tools' },
  { value: 'pet', label: 'Pet Supplies & Services' },
  { value: 'medical', label: 'Medical Supplies & Equipment' },
  { value: 'jewelry', label: 'Jewelry & Accessories' },
  { value: 'florist', label: 'Florist & Gifts' },
  { value: 'baby', label: 'Baby Products & Kids Stores' },
  { value: 'art', label: 'Art & Collectibles' },
  { value: 'music', label: 'Music & Entertainment' },
  { value: 'technology', label: 'Technology & Electronics' },
  { value: 'garden', label: 'Garden & Outdoor Living' },
  { value: 'bakery', label: 'Bakery & Pastry' },
  { value: 'optical', label: 'Optical & Vision Care' },
  { value: 'mobile', label: 'Mobile Phones & Accessories' },
  { value: 'real_estate', label: 'Real Estate & Home Services' },
  { value: 'fitness', label: 'Fitness & Sports' },
  { value: 'entertainment', label: 'Entertainment & Media' },
  { value: 'automotive', label: 'Automotive & Motor Vehicles' },
  { value: 'outdoors', label: 'Outdoors & Camping' },
  { value: 'home', label: 'Home & Living' },
  { value: 'health', label: 'Health & Wellness' },
  { value: 'other', label: 'Other' },
];
